// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe-ExyhXmS-J9h8BGoHHJNATjo4ZqbkWs',
    appId: '1:805447398223:web:282ce097e614d145b68b3a',
    messagingSenderId: '805447398223',
    projectId: 'mycapp-77ad9',
    authDomain: 'mycapp-77ad9.firebaseapp.com',
    storageBucket: 'mycapp-77ad9.appspot.com',
    measurementId: 'G-38RRYSMB79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnyd7chHKtslVR_KVEVRi49s_My-_DW9w',
    appId: '1:805447398223:android:32dab95c7a457ed3b68b3a',
    messagingSenderId: '805447398223',
    projectId: 'mycapp-77ad9',
    storageBucket: 'mycapp-77ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQyiU-yctPnoIysNve0UMwRVP6XOFh74',
    appId: '1:805447398223:ios:a73bba10c6f46aabb68b3a',
    messagingSenderId: '805447398223',
    projectId: 'mycapp-77ad9',
    storageBucket: 'mycapp-77ad9.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNQyiU-yctPnoIysNve0UMwRVP6XOFh74',
    appId: '1:805447398223:ios:e927941675807241b68b3a',
    messagingSenderId: '805447398223',
    projectId: 'mycapp-77ad9',
    storageBucket: 'mycapp-77ad9.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
